apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: pfe
data:
  default.conf: |
    server {
        listen 80;
        index index.php index.html;
        server_name back.eventify.local;
        root /var/www/public;

        # DNS resolver for service discovery
        resolver kube-dns.kube-system.svc.cluster.local valid=10s;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            try_files $uri =404;
            include fastcgi_params;
            fastcgi_pass eventify-app.pfe.svc.cluster.local:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }

        location ~ /\.ht {
            deny all;
        }
    }
