apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventify-pg
  namespace: pfe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventify-pg
  template:
    metadata:
      labels:
        app: eventify-pg
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "eventify_db"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          emptyDir: {}
