apiVersion: v1
kind: PersistentVolume
metadata:
  name: eventify-pgdata-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/postgres
