apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eventify-pvc
  namespace: pfe
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
