apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventify-app
  namespace: pfe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventify-app
  template:
    metadata:
      labels:
        app: eventify-app
    spec:
      containers:
        - name: laravel
          image: ghaithbenali/eventify-v2:latest
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: app-code
              mountPath: /var/www
          env:
            - name: DB_CONNECTION
              value: pgsql
            - name: DB_HOST
              value: eventify-pg
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: eventify_db
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: postgres
      volumes:
        - name: app-code
          hostPath:
            path: /home/gaith/pfe/eventify
            type: Directory
