apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventify-app
  namespace: pfe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventify-app
  template:
    metadata:
      labels:
        app: eventify-app
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox:latest
          command:
            [
              "sh", "-c",
              "mkdir -p /var/www/storage /var/www/bootstrap/cache && \
               chmod -R 775 /var/www/storage /var/www/bootstrap/cache && \
               chown -R 1001:1001 /var/www/storage /var/www/bootstrap/cache"
            ]
          volumeMounts:
            - name: app-code
              mountPath: /var/www
      containers:
        - name: laravel
          image: ghaithbenali/eventify-v2:latest
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: app-code
              mountPath: /var/www
      volumes:
        - name: app-code
          persistentVolumeClaim:
            claimName: eventify-pvc
